export { getQuizDataAustrianAxiom } from "./getQuizDataAustrianAxiom";
export { getQuizDataBridgeMaterial } from "./getQuizDataBridgeMaterial";
export { getQuizDataByzantine } from "./getQuizDataByzantine";
export { getQuizDataHalving } from "./getQuizDataHalving";
export { getQuizDataM0 } from "./getQuizDataM0";
export { getQuizDataM2Explosion } from "./getQuizDataM2Explosion";
export { getQuizDataProfileChoice } from "./getQuizDataProfileChoice";
export { getQuizDataRobinson } from "./getQuizDataRobinson";
export { getQuizDataUtxo } from "./getQuizDataUtxo";
