// Central icon set — Phosphor icons re-exported under the names the app uses.
// This is the ONE place the icon library is bound: the rest of the app imports
// from "@icons" (alias → this file) and never from the underlying package, so a
// future library swap touches only this file. Names are kept identical to the
// previous (lucide) ones so call sites only change their import path.
//
// A handful have no direct Phosphor twin and use the closest match:
//   Pickaxe → Hammer, Activity → Pulse, Telescope → Binoculars.
export {
  Pulse as Activity,
  Warning as AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Medal as Award,
  SealCheck as BadgeCheck,
  Prohibit as Ban,
  Money as Banknote,
  CurrencyBtc as Bitcoin,
  BookOpen,
  BookOpenText,
  Cube as Box,
  Buildings as Building2,
  Check,
  CheckCircle,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CheckCircle as CircleCheck,
  Question as CircleHelp,
  PlusCircle as CirclePlus,
  XCircle as CircleX,
  ClipboardText as ClipboardCheck,
  Clock,
  Coins,
  Columns as Columns3,
  Compass,
  Copy,
  Cpu,
  Door as DoorOpen,
  Equals as Equal,
  Feather,
  Diamond as Gem,
  GitMerge,
  Globe,
  Handshake,
  Hash,
  Question as HelpCircle,
  ClockCounterClockwise as History,
  House as Home,
  Hourglass,
  Tray as Inbox,
  Info,
  Key as KeyRound,
  Bank as Landmark,
  Lightbulb,
  Link as Link2,
  List,
  Lock,
  MapPin,
  Minus,
  Monitor,
  Moon,
  DotsThree as MoreHorizontal,
  Mountains as Mountain,
  Cursor as MousePointerClick,
  PencilSimple as PenLine,
  Hammer as Pickaxe,
  Plus,
  PlusCircle,
  Rabbit,
  ArrowsClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  ArrowClockwise as RotateCw,
  Scales as Scale,
  Scissors,
  Scroll as ScrollText,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  ShieldSlash as ShieldOff,
  ShoppingCart,
  Shuffle,
  Sigma,
  DeviceMobile as Smartphone,
  Sparkle as Sparkles,
  Plant as Sprout,
  Star,
  Sun,
  Target,
  Binoculars as Telescope,
  Tent,
  Timer,
  TrendUp as TrendingUp,
  Triangle,
  Users,
  Vault,
  Wallet,
  X,
  XCircle,
  Lightning as Zap,
  // Icons that were originally imported via multi-line lucide blocks.
  ArrowDownLeft,
  ArrowDownRight,
  ArrowsLeftRight as ArrowLeftRight,
  ArrowsLeftRight as ArrowRightLeft,
  Stack as Blocks,
  Notebook as BookText,
  Briefcase,
  CurrencyCircleDollar as CircleDollarSign,
  Eye,
  EyeSlash as EyeOff,
  Fish,
  Fire as Flame,
  Ghost,
  Gift,
  GraduationCap,
  HardDrive,
  Laptop,
  StackSimple as Layers,
  Envelope as Mail,
  ShareNetwork as Network,
  Receipt,
  PaperPlaneTilt as Send,
  Trophy,
  User,
  UserCheck,
  Waves,
  Wrench,
} from "@phosphor-icons/react";

export type { Icon as IconType } from "@phosphor-icons/react";
