import { type FC } from "react";

import moneyConsuming from "../../../../src/Design/img/money_consuming.jpg";
import moneyCreationCodeline from "../../../../src/Design/img/money_creation_codeline.jpg";
import moneyPrinting from "../../../../src/Design/img/money_printing.webp";
import { Emphasis } from "../../../Design";
import { useTranslation } from "../../../I18n";
import { getQuizDataModule1Synthesis, Illustration, SynthesisQuiz } from "../../../Interactive";
import { PageTemplate, useToggleSimulator } from "../../Shared/";

export const Banking7Page: FC = () => {
  const { t, language } = useTranslation();
  const fr = language === "fr";
  const {
    isActive: isQuizPassed,
    activate: onQuizPassed,
    reset: onQuizReset,
  } = useToggleSimulator();
  const quiz = getQuizDataModule1Synthesis(language);

  return (
    <PageTemplate title={t("nav.tree.synthesis")} showReadingTime={false}>
      <p>
        {fr
          ? "Tu viens de traverser la partie la plus dense. Avant de prendre du recul, mets tes acquis à l'épreuve."
          : "You've just made it through the densest part. Before stepping back, put your understanding to the test."}
      </p>
      <p>
        {fr ? (
          <>
            {quiz.questions.length} questions sur l'ensemble du module.{" "}
            <Emphasis>
              Il te faut au moins {quiz.passThreshold} bonnes réponses pour débloquer la synthèse.
            </Emphasis>
          </>
        ) : (
          <>
            {quiz.questions.length} questions covering the whole module.{" "}
            <Emphasis>
              You need at least {quiz.passThreshold} correct answers to unlock the summary.
            </Emphasis>
          </>
        )}
      </p>

      <SynthesisQuiz
        {...quiz}
        storageKey="synthesisQuiz.module1"
        onPass={onQuizPassed}
        onReset={onQuizReset}
      />

      {isQuizPassed && (
        <>
          <p>{fr ? "Bravo !" : "Well done!"}</p>
          <p>
            {fr
              ? "Tu as traversé la partie la plus dense. Prenons un peu de recul. Si l'on assemble les mécanismes vus jusqu'ici, une image cohérente se dessine. Et elle est inquiétante."
              : "You've made it through the densest part. Now let's take a step back. If we put together the mechanisms we've explored so far, a coherent picture begins to emerge. And it's a troubling one."}
          </p>
          <p>
            {fr ? (
              <>
                L'argent que tu utilises au quotidien (M2) n'est plus une ressource rare adossé à un
                sous-jacent réel. C'est{" "}
                <Emphasis>
                  une monnaie scripturale, créée par les banques commerciales à chaque crédit
                  accordé
                </Emphasis>
                . Cette création monétaire s'inscrit dans un cadre réglementaire et comptable. Mais
                elle reste extensible par nature. Autrement dit : la monnaie est devenue{" "}
                <Emphasis>intrinsèquement facile à produire</Emphasis>.
              </>
            ) : (
              <>
                The money you use every day (M2) is no longer a scarce resource backed by a real
                underlying asset. It is{" "}
                <Emphasis>
                  bank-created money, generated by commercial banks every time a loan is issued
                </Emphasis>
                . This money creation operates within a regulatory and accounting framework. But by
                nature, it remains expandable. In other words: money has become{" "}
                <Emphasis>easy to produce</Emphasis>.
              </>
            )}
            <Illustration
              src={moneyCreationCodeline}
              alt={
                fr
                  ? "Création monétaire via une ligne de code"
                  : "Money creation via a line of code"
              }
              width="30%"
              caption={fr ? "Une simple ligne de code" : "A simple line of code"}
            />
          </p>
          <p>
            {fr ? (
              <>
                Quand le système vacille, un acteur central intervient : la Banque Centrale. Sans
                demander l'avis des épargnants ni des citoyens, elle peut augmenter la monnaie de
                base (M0) en volumes massifs. Notamment via le{" "}
                <Emphasis>Quantitative Easing</Emphasis>, ces fameux rachats d'obligations. Ces
                interventions sauvent le système à court terme.{" "}
                <Emphasis>
                  Mais au prix d'une dilution progressive de la monnaie existante, dès que cette
                  expansion n'est pas compensée par une création de richesse équivalente.
                </Emphasis>
              </>
            ) : (
              <>
                When the system begins to wobble, a central actor steps in: the Central Bank.
                Without asking savers or citizens for consent, it can massively increase the
                monetary base (M0). In particular through <Emphasis>Quantitative Easing</Emphasis>,
                those large-scale bond purchases. These interventions keep the system afloat in the
                short term.{" "}
                <Emphasis>
                  But at the cost of a gradual dilution of the existing currency, whenever that
                  expansion is not matched by an equivalent creation of real wealth.
                </Emphasis>
              </>
            )}
            <Illustration
              src={moneyPrinting}
              alt="Brr printing meme"
              width="40%"
              caption="brrr printing machine!"
            />
          </p>
          <p>
            {fr ? (
              <>
                Cette création monétaire n'arrose pas l'économie de façon uniforme. L'
                <Emphasis>Effet Cantillon</Emphasis>, vous vous en souvenez : l'argent nouvellement
                créé bénéficie d'abord à ceux qui sont proches de la source. Principalement les
                marchés financiers et les détenteurs d'actifs. Résultat : les prix des actifs
                s'envolent. Bourse, immobilier. Pendant que l'économie productive et les revenus du
                travail traînent derrière. <Emphasis>Les écarts de richesse se creusent</Emphasis>.
              </>
            ) : (
              <>
                This money creation does not flow evenly through the economy. You remember the{" "}
                <Emphasis>Cantillon Effect</Emphasis>: newly created money benefits first those
                closest to the source, primarily financial markets and asset holders. The result:
                asset prices soar. Stocks. Real estate. Meanwhile, the productive economy and labor
                income lag behind. <Emphasis>Wealth inequality widens.</Emphasis>
              </>
            )}
          </p>
          <p>
            {fr ? (
              <>
                À terme, ces déséquilibres finissent par atteindre l'économie réelle. Une masse
                monétaire qui gonfle vite, face à une production de biens et services qui progresse
                plus lentement, ça donne <Emphasis>une pression inflationniste durable</Emphasis>.
              </>
            ) : (
              <>
                Eventually, these imbalances spill over into the real economy. When the money supply
                expands rapidly while the production of goods and services grows more slowly, the
                result is <Emphasis>sustained inflationary pressure</Emphasis>.
              </>
            )}
            <Illustration
              src={moneyConsuming}
              alt={fr ? "Consumation des monnaies fiduciaires" : "Fiat currencies burning away"}
              width="30%"
              caption={
                fr
                  ? "Lentement mais sûrement les monnaies fiduciaires se consument"
                  : "Slowly but surely, fiat currencies burn away"
              }
            />
          </p>
          <p>
            {fr ? (
              <>
                <Emphasis>Le constat est structurel</Emphasis>. Ces dynamiques ne sont ni un
                accident de parcours, ni une suite de mauvaises décisions. Elles découlent du{" "}
                <Emphasis>
                  fonctionnement même d'un système monétaire bâti sur l'expansion du crédit et de la
                  dette
                </Emphasis>
                . À chaque déséquilibre court terme, on imprime plus. Et le coût de l'ajustement ?
                On le repousse dans le temps. On le fait porter aux épargnants.
              </>
            ) : (
              <>
                <Emphasis>The problem is structural.</Emphasis> These dynamics are neither accidents
                nor a series of bad decisions. They arise from the{" "}
                <Emphasis>
                  very functioning of a monetary system built on credit and debt expansion
                </Emphasis>
                . Every time a short-term imbalance appears, more money is created. And the cost of
                the adjustment? It is pushed into the future. Passed on to savers.
              </>
            )}
          </p>
          <p>
            {fr
              ? "Et là, une question commence à pointer. Et si on avait un outil différent ? Une monnaie que personne ne pourrait imprimer à volonté. Qui ne dépendrait d'aucun émetteur central. Qui protégerait la valeur de votre épargne dans le temps, presque mécaniquement. Le Graal monétaire, en somme. Mais avant de savoir si cet outil existe, il faut lever le voile sur un mystère qu'on oublie trop souvent."
              : "And then a question begins to emerge. What if there were a different tool? A currency that no one could print at will. One that wouldn't depend on any central issuer. One that would protect the value of your savings over time, almost mechanically. The monetary holy grail, in a way. But before we find out whether such a tool exists, we need to lift the veil on a mystery that is too often overlooked."}
          </p>
          <p>
            {fr ? (
              <>
                <Emphasis>Au fond, c'est quoi l'argent ?</Emphasis> Pourquoi un billet a de la
                valeur, et une feuille d'arbre non ? Pourquoi l'humanité a utilisé l'or pendant des
                millénaires avant de s'en détourner ? Pour comprendre la solution, il faut d'abord
                poser les bases.
              </>
            ) : (
              <>
                <Emphasis>At its core, what is money?</Emphasis> Why does a banknote have value,
                while a leaf does not? Why did humanity use gold for thousands of years before
                moving away from it? To understand the solution, we first need to lay the
                foundations.
              </>
            )}
          </p>
          <p>
            {fr
              ? "Direction la prochaine étape : l'essence de la monnaie."
              : "Next step: the essence of money."}
          </p>
        </>
      )}
    </PageTemplate>
  );
};
